package com.company;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        System.out.print("Input password: ");
        Scanner kb = new Scanner(System.in);
        String pass = kb.nextLine();
        System.out.println("Your Password generated by MD5 is: " + MD5.getMd5(pass));
        kb.close();
    }
}
